In [1]:
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 안녕하세요
안녕하세요


In [2]:
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [3]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [4]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [5]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1][2]

3.14

In [7]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [8]:
arVal[0][2]

't'

In [9]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [10]:
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [11]:
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [12]:
arVal.sum()

AttributeError: 'list' object has no attribute 'sum'

In [13]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [15]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [16]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [17]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [18]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [19]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [20]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [21]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [22]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [25]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [26]:
pandas_series[0]

30

In [27]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [28]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [29]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [30]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [31]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [32]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [33]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [34]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [35]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [36]:
# column 삭제
del df['score']

In [37]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [38]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [39]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [40]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [41]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0  0.791724  0.419364 -1.577875 -0.996333 -0.623312
1 -0.869457  0.507516 -0.310372 -0.376604  0.296590
2 -0.142798  1.235124  0.288202  0.663535 -0.273286
3  0.420898 -0.198062 -0.089311 -2.281557 -0.470962
4 -0.332584  0.223794  0.570768 -0.049232 -1.994702

In [42]:
# 최대값
df.max()

A    0.791724
B    1.235124
C    0.570768
D    0.663535
E    0.296590
dtype: float64

In [43]:
# 최소값
df.min()

A   -0.869457
B   -0.198062
C   -1.577875
D   -2.281557
E   -1.994702
dtype: float64

In [44]:
# 평균
df.mean()

A   -0.026443
B    0.437547
C   -0.223718
D   -0.608038
E   -0.613134
dtype: float64

In [45]:
# 표준편차
df.std()

A    0.649508
B    0.522265
C    0.829546
D    1.110649
E    0.847369
dtype: float64

In [46]:
# 누적값
df.cumsum()

A         B         C         D         E
0  0.791724  0.419364 -1.577875 -0.996333 -0.623312
1 -0.077733  0.926880 -1.888247 -1.372937 -0.326722
2 -0.220530  2.162004 -1.600045 -0.709401 -0.600008
3  0.200367  1.963941 -1.689356 -2.990958 -1.070970
4 -0.132217  2.187736 -1.118589 -3.040190 -3.065672

In [47]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.026443  0.437547 -0.223718 -0.608038 -0.613134
std    0.649508  0.522265  0.829546  1.110649  0.847369
min   -0.869457 -0.198062 -1.577875 -2.281557 -1.994702
25%   -0.332584  0.223794 -0.310372 -0.996333 -0.623312
50%   -0.142798  0.419364 -0.089311 -0.376604 -0.470962
75%    0.420898  0.507516  0.288202 -0.049232 -0.273286
max    0.791724  1.235124  0.570768  0.663535  0.296590

In [48]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0  0.791724  0.419364 -1.577875 -0.996333 -0.623312        X
1 -0.869457  0.507516 -0.310372 -0.376604  0.296590        Y
2 -0.142798  1.235124  0.288202  0.663535 -0.273286        X
3  0.420898 -0.198062 -0.089311 -2.281557 -0.470962        Y
4 -0.332584  0.223794  0.570768 -0.049232 -1.994702        Z

In [49]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X         0.324463  0.827244 -0.644836 -0.166399 -0.448299
Y        -0.224280  0.154727 -0.199842 -1.329080 -0.087186
Z        -0.332584  0.223794  0.570768 -0.049232 -1.994702